# Generated by Django 4.2.14 on 2024-07-12 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_name_alter_profile_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date_birth',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sex',
        ),
    ]
