# Generated by Django 4.2.14 on 2024-07-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_profile_address_remove_profile_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileimage',
            old_name='user_id',
            new_name='user_profile_id',
        ),
    ]
