# Generated by Django 4.2.14 on 2024-07-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_user_id_userprofileimage_user_profile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileimage',
            old_name='user_profile_id',
            new_name='user_profile',
        ),
    ]
